# Generated by Django 5.0.1 on 2024-01-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('grade', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
