# Generated by Django 5.0.1 on 2024-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
